---
 - hosts: 192.168.150.30
   tasks:
     - name: Fetch the file from the ogi to ansible tower
       run_once: yes
       fetch: src=/home/netcool/advanced_agents_xlinux_8.1.4.0.13.tar dest=buffer/ flat=yes

 - hosts: 192.168.150.29
   tasks:
     - name: Copy the file from ansible tower to ema
       copy: src=buffer/advanced_agents_xlinux_8.1.4.0.13.tar dest=/home/netcool/ 
     - name: Extract tar file
       ansible.builtin.unarchive:
         src: /home/netcool/advanced_agents_xlinux_8.1.4.0.13.tar
         dest: /home/netcool
